githubRepoOwner: mllvzeth
githubRepoName: python-ai-agent
githubHost: github.com
githubRemote: origin
githubBranch: main
requireChecks: true
requireApproval: false
mergeMethod: rebase
mergeQueue: false
prTemplateType: stack
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
